-- 01_schema.sql
-- Schema for retail analytics mini-project (PostgreSQL)

-- Assumes you are already connected to database: retail_analytics

DROP VIEW IF EXISTS v_customer_ltv;
DROP VIEW IF EXISTS v_revenue_by_region_channel;
DROP VIEW IF EXISTS v_product_rank_in_category;
DROP VIEW IF EXISTS v_revenue_by_product;
DROP VIEW IF EXISTS v_daily_revenue_mavg;
DROP VIEW IF EXISTS v_daily_revenue_window;
DROP VIEW IF EXISTS v_daily_revenue;
DROP VIEW IF EXISTS v_sales_fact;

DROP VIEW IF EXISTS v_order_items_quality;
DROP VIEW IF EXISTS v_order_items_clean;
DROP VIEW IF EXISTS v_products_clean;
DROP VIEW IF EXISTS v_orders_clean;
DROP VIEW IF EXISTS v_customers_clean;

DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS customers;

CREATE TABLE products (
    product_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name TEXT NOT NULL,
    category     TEXT NOT NULL,
    brand        TEXT,
    unit_price   NUMERIC(10,2) NOT NULL,
    cost         NUMERIC(10,2) NOT NULL
);

CREATE TABLE customers (
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  TEXT NOT NULL,
    last_name   TEXT NOT NULL,
    email       TEXT,
    gender      TEXT,
    city        TEXT,
    region      TEXT,
    signup_date DATE
);

CREATE TABLE orders (
    order_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id    INTEGER NOT NULL REFERENCES customers(customer_id),
    order_date     DATE NOT NULL,
    order_time     TIME,
    order_status   TEXT,
    order_region   TEXT,
    order_channel  TEXT,
    payment_method TEXT
);

CREATE TABLE order_items (
    order_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      INTEGER NOT NULL REFERENCES orders(order_id),
    product_id    INTEGER NOT NULL REFERENCES products(product_id),
    quantity      INTEGER NOT NULL,
    unit_price    NUMERIC(10,2) NOT NULL,
    discount      NUMERIC(5,2) DEFAULT 0.0,
    line_total    NUMERIC(10,2) NOT NULL
);
